### PR TITLE
removed default dependencies fixed X11 start of msui

### PR DESCRIPTION
**Pull request by ReimarBauer**

### CODE REVIEW

**Comment by joernu76** [comment]
This still generates a core dump?

**Comment by joernu76** [comment]
It also looks like *this* mambaforge container is based on ubuntu, which makes adding debian repos a BAD thing.
I think that this is wrong since changing over to mambaforge.

I would stick with debian and installing mamba/conda manually from scratch. Much more stable.

**Comment by joernu76** [comment]
The debian stuff happens in the workflow.

**Comment by ReimarBauer** [comment]
we better switch to mambaforge, because that has not any dependency to anaconda builds. Also the debian stuff added is not needed when we use ubuntu.

I currently try to solve testing problems.

**Comment by joernu76** [comment]
I would even say that the debian stuff is almost certainly causing issues (potentially even the core dump) when using an ubuntu container.

What I dislike is that we need to *know* what is used to avoid such shenanigans and using another base container prevents us from knowing what we are doing.
I'd vastly prefer starting with minimal debian (because it changes only every three years, not every six month!) and download and install miniforge ourselves than basing it on mambaforge (I am opposed (but not strongly opposed) against ubuntu for a variety of reasons).

The current state is obviously the least desirable, as we create three containers based on two different distributions, which thus cannot be handled identically.

Also, I strongly favor getting rid of the three branches first and creating them using a single branch with directories. 
In the current state, it is very difficult to know what is executed in which branch due to differences in, e.g., the workflow directory.
Impossible to keep consistent and thus unmaintainable.

**Comment by ReimarBauer** [comment]
the three branches where an evolution we should cut off. That started historical and is very confusing now.

mambaforge is the suggested image by the conda-forge folks. The QT X11 problems were easier to solve as with the debian package. With mambaforge I don't expect much differences to the build on the CIs of conda-forge. Also there is a large developer group who could fix problems quick.

**Comment by joernu76** [comment]
The workflow enters debian repos into the image for testing and installs debian package. If you keep on using mambaforge, which is ubuntu based, you must update the workflow as well.

**Comment by joernu76** [comment]
Another argument for using a simple debian/ubuntu container would be that this would replicate the "normal" installation a user or developer would follow. I.e. download micromamba/forge and install it.
No developer will use mamba-forge as a basis.
As such, we would discover issue more readily by basing everything on debian/ubuntu container.

Also, I believe many more people use installers compared to docker-containers, i.e. it is likely that it is better tested.

**Comment by ReimarBauer** [comment]
As long as we need a container, we are not close to a user installation. We use e.g. a recent OS version, also a headless setup. Currently we test only on one python version and one OS at all. 

That recommended container has much downloads 
https://hub.docker.com/r/condaforge/mambaforge
and we would need to do a similar (duplicated) configuration and lookup this often like https://github.com/conda-forge/miniforge-images/blob/master/ubuntu/Dockerfile

**Review by joernu76 — APPROVED** [review]

**Comment by joernu76** [comment]
If we start with a minimal ubuntu container; because that is as close to a (Linux) user system as it gets. The "testing" dockerfile would then specify, ideally exactly, the installation instructions for developers. I.e. everything before checking out mss.

The "develop" dockerfile should, ideally, simply install anaconda(-forge) and do a local build.
The "stable" dockerfile should simply install anaconda(-forge) and install mss from conda-forge.

As such, the stable dockerfile should do *exactly* as our user installation instructions (for linux).

Problems: having proper dependencies for testing/develop versions. I have no good idea here, but that'd be my vision for how it should look like in the end.

**Comment by ReimarBauer** [comment]
the testing needs to take care about different version of packages (stable, develop) as we have it now.

stable image should be just created after we have a build on conda-forge, 2h after a release. Currently I trigger RTFD build manually (not ideal) but this could be the same trigger. 

develop is the more challenging one, ideally it can do this by a conda build, but if we have to set fixations to a python version we probably could replace this by a tox setup to build at least on the python versions which are on conda-forge for linux.

**Comment by ReimarBauer** [comment]
My favorite way to bootstrap a docker image these days is micromamba + conda-lock --kind=explicit
from conda-forge chat by minrk, https://github.com/minrk/simula-summer-school/blob/84eae1e195eeb55b079a6b930baf27dfab101a4f/image/entrypoint.sh

But for activation, I like to use an entrypoint script like this one that does:
#!/bin/bash -l so it starts a login shell (sources /etc/profile.d and friends, which includes conda.sh)
conda activate root to activate the env
exec "$@" to execute the actual command

**Pull request merged**
